### ISSUE TITLE
add support for qemu (RDT-261)

### ISSUE THREAD

**Issue by greenaddress** [espressif/esp-idf-ci-action#22]
It would be nice if qemu was available as a command in the docker image (or separate action)

**Comment by kumekay** [comment]
@greenaddress It's an excellent idea. I cannot tell you an exact timeline for this, but we are considering implementing it. So let's keep this issue open

**Comment by greenaddress** [comment]
thanks @kumekay 

If it helps, this is how we compile qemu optimized for esp32 use and size:

https://github.com/Blockstream/Jade/blob/master/Dockerfile#L19

**Comment by kumekay** [comment]
Hi @greenaddress  

Xtensa QEMU was added to the docker file recently: https://github.com/espressif/esp-idf/blob/cfef24863f1acd4418227a727dbb6e356438a385/tools/docker/Dockerfile#L92-L102
