### ISSUE TITLE
Clean up old releases and tags (RDT-748)

### ISSUE THREAD

**Issue by Gussy** [espressif/esp-idf-ci-action#39]
At the time of writing this repository has 5 [releases](https://github.com/espressif/esp-idf-ci-action/releases), listed newest to oldest:
[v1.1.0](https://github.com/espressif/esp-idf-ci-action/tree/v1.1.0)
[v1.0.0](https://github.com/espressif/esp-idf-ci-action/tree/v1.0.0)
[rust-latest](https://github.com/espressif/esp-idf-ci-action/tree/rust-latest)
[v4.3](https://github.com/espressif/esp-idf-ci-action/tree/v4.3)
[v4.2.1](https://github.com/espressif/esp-idf-ci-action/tree/v4.2.1)

Dependency tracking tools like Dependabot identify the old v4.x releases as newer than the latest v1.1.0 release, because the semantic version is greater.

Can the old releases and tags be deleted, to keep consistency with the newer v1.x releases?

**Comment by kumekay** [comment]
@Gussy Yes, I've cleaned the old tags for IDF versions which are not maintained anymore. Hope Dependabot won't be confused.
