### ISSUE TITLE
CMakeLists.txt not found in project directory (RDT-757)

### ISSUE THREAD

**Issue by epneo-banuprakash** [espressif/esp-idf-ci-action#40]
Hi,
I am facing the issue **CMakeLists.txt not found in project directory** 

- name: Build compile_commands.json
        uses: espressif/esp-idf-ci-action@v1
        with:
            esp_idf_version: ${{ matrix.idf_ver }}
            target: ${{ matrix.idf_target }}
            path: ${{ github.workspace }}

Here path is specified as ${{ github.workspace }} but i got this error like CMakeLists.txt not found in project directory /app/repo_name/home/runner/work/repo_name/repo_name.

Actuall Error: **CMakeLists.txt not found in project directory /app/epneo/FW_IG_AIR/home/runner/work/FW_IG_AIR/FW_IG_AIR**

Why is not taking from the specified path??

**Comment by kumekay** [comment]
@epneo-banuprakash path is supposed to be relative and needed only for the case if you have multiple projects in the repository.

You can remove `path` entirely in your case.

**Comment by epneo-banuprakash** [comment]
It is worked for me, after removing the path , Thanks.
